[package]
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
edition = "2021"
readme = "README.md"
name = "nixie-counter"
version = "0.1.0"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-rtic = "1.1"
debouncr = "0.2.2"
embedded-hal = "0.2"
panic-rtt-target = { version = "0.1.0", features = ["cortex-m"] }
stm32f1 = { version = "0.14", features = ["stm32f103", "rt"] }
stm32f1xx-hal = { version = "0.9", features = ["stm32f103", "medium", "rtic"] }
systick-monotonic = "1"
rtt-target = { version = "0.3", features = ["cortex-m"] }

[[bin]]
name = "nixie-counter"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
