[package]
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
edition = "2021"
readme = "README.md"
name = "nixie-counter"
version = "0.1.0"

[dependencies]
atat = { version = "0.17", features = ["defmt"] }
bbqueue = "0.5"
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
cortex-m-rtic = "1.1"
debouncr = "0.2.2"
defmt = "0.3"
defmt-rtt = "0.4"
embedded-hal = "0.2"
embedded-nal = "0.6"
esp-at-nal = { git = "https://github.com/dbrgn/rt-esp-at-nal/", branch = "defmt-errors", features = ["defmt"] }
fugit = "0.3.3"
fugit-timer = "0.1.2"
heapless = "0.7"
nb = "1"
numtoa = "0.2"
stm32f1 = { version = "0.15.1", features = ["stm32f103", "rt"] }
stm32f1xx-hal = { git = "https://github.com/stm32-rs/stm32f1xx-hal/", branch = "ehal", features = ["stm32f103", "medium", "rtic"] }
systick-monotonic = "1"

[[bin]]
name = "nixie-counter"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
