[package]
name = "firmware"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "firmware"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["embassy"]
embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[dependencies]
anyhow = "1"
futures-util = "0.3"
log = { version = "0.4", default-features = false }
embassy-futures = { version = "0.1" }
embedded-svc = { version = "0.28", default-features = false, features = ["std", "alloc"] }
esp-idf-svc = { version = "0.49", default-features = false, features = ["alloc", "binstart", "std", "native"] }

[build-dependencies]
embuild = "0.32.0"
