[default.general]
chip = "STM32F103C8"

[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true
restore_unwritten_bytes = false

[default.rtt]
enabled = true
channels = [
    { up = 0, up_mode = "BlockIfFull", format = "Defmt" },
]
