on:
  push:
    branches: [master, main]
  pull_request:

name: CI

jobs:

  firmware-build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-10-10
          target: riscv32imc-unknown-none-elf
          override: true
      - name: Run check
        env:
          WIFI_SSID: "example-ssid"
          WIFI_PASS: "example-pass"
          SPACEAPI_SENSOR_ENDPOINT: "http://example.com/sensors/people_now_present/"
        run: cd firmware && cargo check --target riscv32imc-unknown-none-elf --release

  rustfmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
          components: rustfmt
          override: true
      - run: cd firmware && cargo fmt -- --check
